### ISSUE TITLE
JSON Merges Style Inherits by Default

### ISSUE THREAD

**Issue by Averylamp** [mosaicml/yahp#91]
Want to move from our custom inherits scheme to a scheme such as JSON merge to allow for more flexibility when merging different parameter types.

**Comment by siriuslee** [comment]
This all looks good to me. My only request on the implementation side of things is that the `merge` function be one that can be called without first writing to `yaml` files. This would obviously limit to some degree the ability to do nested inheritance, but something like `merge(base, head, strategy="concat")` would help a lot.

**Comment by Averylamp** [comment]
Talked offline, but basically would also want the ability to call a functional form of merge
```python
def merge(base_yaml: Dict[str: Any], 
                 *inherited_yamls: Dict[str: Any], 
                 operator: Operator=Operator.update,
                 ) -> Dict[str:Any]:
   # Where `inherited_yamls` are iteratively merged (note: Source is not specified because inhertiance from root is assumed)
```

------
Functionally means that for the following example
`1.yaml`
``` yaml
produce:
  tomatoes:
    status: ripe
    number: 12
```
`2.yaml`
``` yaml
produce:
  potatoes:
    type: russell
```

`3.yaml`
``` yaml
produce:
  tomatoes:
    number: 15
```
`merge_stuff.py`
```python
out = merge(`1.yaml`, `2.yaml`, `3.yaml`, operator=Operator.update)
```
`out`
```yaml
produce:
  tomatoes:
    status: ripe
    number: 15
  potatoes:
    type: russell

```


------
Which is notably equivalent to the yaml
`1.yaml`
``` yaml
inherits:
- `2.yaml`
- `3.yaml`
produce:
  tomatoes:
    status: ripe
    number: 12
```
